name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./build-android.sh

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.8'
    - name: build
      run: ./build-ios.sh

  watchos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./build-watchos.sh
